exceptions = {'__init__': None,
 'aci_aaa_certificate_authority': None,
 'aci_aaa_custom_privilege': None,
 'aci_aaa_domain': None,
 'aci_aaa_key_ring': None,
 'aci_aaa_role': None,
 'aci_aaa_security_default_settings': None,
 'aci_aaa_ssh_auth': None,
 'aci_aaa_user': None,
 'aci_aaa_user_certificate': None,
 'aci_aaa_user_domain': None,
 'aci_aaa_user_role': None,
 'aci_access_port_block_to_access_port': None,
 'aci_access_port_to_interface_policy_leaf_profile': None,
 'aci_access_span_dst_group': None,
 'aci_access_span_filter_group': None,
 'aci_access_span_filter_group_entry': None,
 'aci_access_span_src_group': {'destination_group': ['spanSpanLbl',
                                                     'attributes',
                                                     'name']},
 'aci_access_span_src_group_src': None,
 'aci_access_span_src_group_src_path': None,
 'aci_access_spine_interface_profile': None,
 'aci_access_spine_interface_profile_to_spine_switch_profile': None,
 'aci_access_spine_interface_selector': None,
 'aci_access_spine_switch_profile': None,
 'aci_access_spine_switch_selector': None,
 'aci_access_sub_port_block_to_access_port': None,
 'aci_access_switch_policy_group': None,
 'aci_action_rule_additional_communities': None,
 'aci_action_rule_set_as_path': None,
 'aci_action_rule_set_as_path_asn': None,
 'aci_aep': None,
 'aci_aep_to_domain': None,
 'aci_aep_to_epg': None,
 'aci_ap': None,
 'aci_bd': {'endpoint_retention_action': ['fvRsBdToEpRet',
                                          'attributes',
                                          'resolveAct'],
            'endpoint_retention_policy': ['fvRsBdToEpRet',
                                          'attributes',
                                          'tnFvEpRetPolName'],
            'first_hop_security_policy': ['fvRsBDToFhs',
                                          'attributes',
                                          'tnFhsBDPolName'],
            'igmp_snoop_policy': ['fvRsIgmpsn',
                                  'attributes',
                                  'tnIgmpSnoopPolName'],
            'ipv6_nd_policy': ['fvRsBDToNdP', 'attributes', 'tnNdIfPolName'],
            'mld_snoop_policy': ['fvRsMldsn',
                                 'attributes',
                                 'tnMldSnoopPolName'],
            'monitoring_policy': ['fvRsABDPolMonPol',
                                  'attributes',
                                  'tnMonEPGPolName'],
            'route_profile': ['fvRsBDToProfile',
                              'attributes',
                              'tnRtctrlProfileName'],
            'route_profile_l3out': ['fvRsBDToProfile',
                                    'attributes',
                                    'tnL3extOutName'],
            'vlan': ['fvAccP', 'attributes', 'encap'],
            'vrf': ['fvRsCtx', 'attributes', 'tnFvCtxName']},
 'aci_bd_dhcp_label': {'dhcp_option': ['dhcpRsDhcpOptionPol',
                                       'attributes',
                                       'tnDhcpOptionPolName']},
 'aci_bd_rogue_exception_mac': None,
 'aci_bd_subnet': {'nd_prefix_policy': ['fvRsNdPfxPol',
                                        'attributes',
                                        'tnNdPfxPolName'],
                   'route_profile': ['fvRsBDSubnetToProfile',
                                     'attributes',
                                     'tnRtctrlProfileName'],
                   'route_profile_l3_out': ['fvRsBDSubnetToProfile',
                                            'attributes',
                                            'tnL3extOutName']},
 'aci_bd_to_l3out': None,
 'aci_bd_to_netflow_monitor_policy': None,
 'aci_bfd_multihop_node_policy': None,
 'aci_bgp_address_family_context_policy': None,
 'aci_bgp_best_path_policy': None,
 'aci_bgp_peer_prefix_policy': None,
 'aci_bgp_route_summarization_policy': None,
 'aci_bgp_rr_asn': None,
 'aci_bgp_rr_node': None,
 'aci_bgp_timers_policy': None,
 'aci_bulk_static_binding_to_epg': None,
 'aci_cloud_ap': None,
 'aci_cloud_aws_provider': None,
 'aci_cloud_bgp_asn': None,
 'aci_cloud_cidr': None,
 'aci_cloud_ctx_profile': None,
 'aci_cloud_epg': None,
 'aci_cloud_epg_selector': None,
 'aci_cloud_external_epg': None,
 'aci_cloud_external_epg_selector': None,
 'aci_cloud_provider': None,
 'aci_cloud_region': None,
 'aci_cloud_subnet': None,
 'aci_cloud_vpn_gateway': None,
 'aci_cloud_zone': None,
 'aci_config_export_policy': None,
 'aci_config_rollback': None,
 'aci_config_snapshot': None,
 'aci_contract': None,
 'aci_contract_export': None,
 'aci_contract_subject': None,
 'aci_contract_subject_to_filter': None,
 'aci_contract_subject_to_service_graph': None,
 'aci_dhcp_option': None,
 'aci_dhcp_option_policy': None,
 'aci_dhcp_relay': None,
 'aci_dhcp_relay_provider': None,
 'aci_dns_domain': None,
 'aci_dns_profile': None,
 'aci_dns_provider': None,
 'aci_domain': None,
 'aci_domain_to_encap_pool': None,
 'aci_domain_to_vlan_pool': {'aci_mo': ['infraRsVlanNs', 'attributes', 'tDn']},
 'aci_encap_pool': None,
 'aci_encap_pool_range': None,
 'aci_epg': None,
 'aci_epg_monitoring_policy': None,
 'aci_epg_subnet': {'nd_prefix_policy': ['fvRsNdPfxPol',
                                         'attributes',
                                         'tnNdPfxPolName'],
                    'route_profile': ['fvRsBDSubnetToProfile',
                                      'attributes',
                                      'tnRtctrlProfileName'],
                    'route_profile_l3out': ['fvRsBDSubnetToProfile',
                                            'attributes',
                                            'tnL3extOutName']},
 'aci_epg_to_contract': None,
 'aci_epg_to_contract_interface': None,
 'aci_epg_to_contract_master': None,
 'aci_epg_to_domain': None,
 'aci_epg_useg_attribute_block_statement': None,
 'aci_epg_useg_attribute_simple_statement': None,
 'aci_esg': None,
 'aci_esg_contract_master': None,
 'aci_esg_epg_selector': None,
 'aci_esg_ip_subnet_selector': None,
 'aci_esg_tag_selector': None,
 'aci_esg_to_contract': None,
 'aci_fabric_external_connection_profile': None,
 'aci_fabric_external_routing_profile': None,
 'aci_fabric_interface_policy_group': None,
 'aci_fabric_leaf_profile': None,
 'aci_fabric_leaf_switch_assoc': None,
 'aci_fabric_management_access': None,
 'aci_fabric_management_access_https_cipher': None,
 'aci_fabric_node': None,
 'aci_fabric_node_control': None,
 'aci_fabric_pod': None,
 'aci_fabric_pod_connectivity_profile': None,
 'aci_fabric_pod_external_tep': None,
 'aci_fabric_pod_policy_group': None,
 'aci_fabric_pod_profile': None,
 'aci_fabric_pod_remote_pool': None,
 'aci_fabric_pod_selector': None,
 'aci_fabric_scheduler': None,
 'aci_fabric_span_dst_group': None,
 'aci_fabric_span_src_group': {'destination_group': ['spanSpanLbl',
                                                     'attributes',
                                                     'name']},
 'aci_fabric_span_src_group_src': None,
 'aci_fabric_span_src_group_src_node': None,
 'aci_fabric_span_src_group_src_path': None,
 'aci_fabric_spine_profile': None,
 'aci_fabric_spine_switch_assoc': None,
 'aci_fabric_switch_block': None,
 'aci_fabric_switch_policy_group': None,
 'aci_fabric_wide_settings': None,
 'aci_file_remote_path': None,
 'aci_filter': None,
 'aci_filter_entry': None,
 'aci_firmware_group': None,
 'aci_firmware_group_node': None,
 'aci_firmware_policy': None,
 'aci_firmware_source': None,
 'aci_igmp_interface_policy': None,
 'aci_interface_blacklist': None,
 'aci_interface_config': None,
 'aci_interface_description': None,
 'aci_interface_policy_bfd': None,
 'aci_interface_policy_bfd_multihop': None,
 'aci_interface_policy_cdp': None,
 'aci_interface_policy_eigrp': None,
 'aci_interface_policy_fc': None,
 'aci_interface_policy_hsrp': None,
 'aci_interface_policy_l2': None,
 'aci_interface_policy_leaf_breakout_port_group': None,
 'aci_interface_policy_leaf_fc_policy_group': None,
 'aci_interface_policy_leaf_policy_group': None,
 'aci_interface_policy_leaf_profile': None,
 'aci_interface_policy_leaf_profile_fex_policy_group': None,
 'aci_interface_policy_link_level': None,
 'aci_interface_policy_lldp': None,
 'aci_interface_policy_mcp': None,
 'aci_interface_policy_ospf': None,
 'aci_interface_policy_pim': None,
 'aci_interface_policy_port_channel': None,
 'aci_interface_policy_port_security': None,
 'aci_interface_policy_spanning_tree': None,
 'aci_interface_policy_spine_policy_group': None,
 'aci_interface_policy_storm_control': None,
 'aci_interface_selector_to_switch_policy_leaf_profile': None,
 'aci_key_policy': None,
 'aci_keychain_policy': None,
 'aci_l2out': None,
 'aci_l2out_extepg': None,
 'aci_l2out_extepg_to_contract': None,
 'aci_l2out_logical_interface_path': None,
 'aci_l2out_logical_interface_profile': None,
 'aci_l2out_logical_node_profile': None,
 'aci_l3out': None,
 'aci_l3out_bfd_interface_profile': None,
 'aci_l3out_bfd_multihop_interface_profile': None,
 'aci_l3out_bgp_peer': None,
 'aci_l3out_bgp_protocol_profile': None,
 'aci_l3out_dhcp_relay_label': None,
 'aci_l3out_eigrp_interface_profile': None,
 'aci_l3out_extepg': None,
 'aci_l3out_extepg_to_contract': None,
 'aci_l3out_extsubnet': None,
 'aci_l3out_floating_svi': None,
 'aci_l3out_floating_svi_path': None,
 'aci_l3out_floating_svi_path_secondary_ip': None,
 'aci_l3out_floating_svi_secondary_ip': None,
 'aci_l3out_hsrp_group': None,
 'aci_l3out_hsrp_interface_profile': None,
 'aci_l3out_hsrp_secondary_vip': None,
 'aci_l3out_interface': None,
 'aci_l3out_interface_secondary_ip': None,
 'aci_l3out_logical_interface_profile': None,
 'aci_l3out_logical_interface_profile_ospf_policy': None,
 'aci_l3out_logical_interface_vpc_member': None,
 'aci_l3out_logical_node': None,
 'aci_l3out_logical_node_profile': None,
 'aci_l3out_route_tag_policy': None,
 'aci_l3out_static_routes': None,
 'aci_l3out_static_routes_nexthop': None,
 'aci_l3out_to_sr_mpls_infra_l3out': None,
 'aci_maintenance_group': None,
 'aci_maintenance_group_node': None,
 'aci_maintenance_policy': None,
 'aci_match_as_path_regex_term': None,
 'aci_match_community_factor': None,
 'aci_match_community_regex_term': None,
 'aci_match_community_term': None,
 'aci_match_route_destination': None,
 'aci_match_rule': None,
 'aci_netflow_exporter_policy': None,
 'aci_netflow_monitor_policy': None,
 'aci_netflow_monitor_to_exporter': None,
 'aci_netflow_record_policy': None,
 'aci_node_block': None,
 'aci_node_mgmt_epg': None,
 'aci_ntp_policy': None,
 'aci_ntp_server': None,
 'aci_pim_route_map_entry': None,
 'aci_pim_route_map_policy': None,
 'aci_qos_custom_policy': None,
 'aci_qos_dot1p_class': None,
 'aci_qos_dscp_class': None,
 'aci_rest': None,
 'aci_route_control_context': None,
 'aci_route_control_profile': None,
 'aci_snmp_client': None,
 'aci_snmp_client_group': None,
 'aci_snmp_community_policy': None,
 'aci_snmp_policy': None,
 'aci_snmp_user': None,
 'aci_static_binding_to_epg': None,
 'aci_static_node_mgmt_address': None,
 'aci_subject_label': None,
 'aci_switch_leaf_selector': None,
 'aci_switch_policy_leaf_profile': None,
 'aci_switch_policy_vpc_protection_group': None,
 'aci_syslog_group': None,
 'aci_syslog_remote_dest': None,
 'aci_syslog_source': None,
 'aci_system': None,
 'aci_system_banner': None,
 'aci_system_connectivity_preference': None,
 'aci_system_endpoint_controls': None,
 'aci_system_global_aes_passphrase_encryption': None,
 'aci_taboo_contract': None,
 'aci_tag': None,
 'aci_tenant': None,
 'aci_tenant_action_rule_profile': None,
 'aci_tenant_ep_retention_policy': None,
 'aci_tenant_span_dst_group': None,
 'aci_tenant_span_src_group': {'dst_group': ['spanSpanLbl',
                                             'attributes',
                                             'name']},
 'aci_tenant_span_src_group_src': {'tdn': ['spanRsSrcToEpg',
                                           'attributes',
                                           'tDn']},
 'aci_tenant_span_src_group_to_dst_group': None,
 'aci_vlan_pool': None,
 'aci_vlan_pool_encap_block': None,
 'aci_vmm_controller': None,
 'aci_vmm_credential': None,
 'aci_vmm_uplink': None,
 'aci_vmm_uplink_container': None,
 'aci_vmm_vswitch_policy': None,
 'aci_vrf': None,
 'aci_vrf_leak_internal_subnet': None,
 'aci_vrf_multicast': None,
 'aci_vzany_to_contract': None}
