paramAliasMap = {'aci_fabric_pod_policy_group': {'name': ['policy_group',
   'policy_group_name',
   'pod_policy_group'],
  'date_time_policy': ['ntp_policy'],
  'isis_policy': None,
  'coop_group_policy': ['coop_policy'],
  'bgp_rr_policy': None,
  'management_access_policy': ['management_policy', 'mgmt_policy'],
  'snmp_policy': None,
  'macsec_policy': None,
  'name_alias': ['nameAlias'],
  'state': None},
 'aci_esg_contract_master': {'tenant': ['tenant_name'],
  'ap': ['app_profile', 'app_profile_name'],
  'esg': ['esg_name'],
  'contract_master_ap': None,
  'contract_master_esg': None,
  'state': None,
  'name_alias': None,
  'contract_master': ['tDn']},
 'aci_l3out_floating_svi': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['interface_profile_name', 'logical_interface'],
  'state': None,
  'pod_id': None,
  'node_id': None,
  'address': ['addr', 'ip_address'],
  'link_local_address': ['llAddr'],
  'mac_address': ['mac'],
  'mtu': ['mtu'],
  '_dad': None,
  'mode': ['mode'],
  'encap': ['encap'],
  'encap_scope': ['encapScope'],
  'auto_state': ['autostate'],
  'external_bridge_group_profile': None,
  'ipv6_dad': ['ipv6Dad'],
  '"ext-svi"': ['ifInstT']},
 'aci_l3out_bgp_peer': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'description': ['descr'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['interface_profile_name', 'logical_interface'],
  'state': None,
  'pod_id': None,
  'node_id': None,
  'path_ep': None,
  'peer_ip': ['addr'],
  'remote_asn': None,
  'ctrl': ['ctrl'],
  'ctrl_ext': ['ctrlExt'],
  'peerCtrl': ['peerCtrl'],
  'addrTCtrl': ['addrTCtrl'],
  'privateASctrl': ['privateASctrl'],
  'ttl': ['ttl'],
  'weight': ['weight'],
  'admin_state': ['adminSt'],
  'allow_self_as_count': ['allowedSelfAsCnt'],
  'peer_type.replace("_"': ['peerT']},
 'aci_bgp_timers_policy': {'tenant': ['tenant_name'],
  'bgp_timers_policy': ['bgp_timers_policy_name', 'name'],
  'graceful_restart_controls': ['grCtrl'],
  'hold_interval': ['holdIntvl'],
  'keepalive_interval': ['kaIntvl'],
  'max_as_limit': ['maxAsLimit'],
  'stale_interval': ['staleIntvl'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_l2out': {'bd': None,
  'out': ['name'],
  'domain': None,
  'vlan': None,
  'description': ['descr'],
  'state': None,
  'tenant': None,
  'name_alias': None,
  'l2out': ['name'],
  '"uni/tn-{0}/l2out-{1}".format(tenant': ['dn']},
 'aci_l3out_hsrp_group': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['interface_profile_name', 'logical_interface'],
  'hsrp_interface_group': ['name', 'hsrp_group'],
  'group_id': ['groupId'],
  'ip': ['ip'],
  'mac': ['mac'],
  'group_name': ['groupName'],
  'description': ['descr'],
  'group_type': ['groupAf'],
  'ip_obtain_mode': ['ipObtainMode'],
  'group_policy': None,
  'state': None},
 'aci_subject_label': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'external_epg': ['extepg', 'extepg_name', 'external_epg_name'],
  'contract': ['contract_name'],
  'subject': ['subject_name'],
  'ap': ['app_profile',
   'app_profile_name',
   'application_profile',
   'application_profile_name'],
  'epg': ['epg_name'],
  'esg': ['esg_name'],
  'complement': ['isComplement'],
  'description': ['descr'],
  'subject_label': ['subject_label_name', 'name', 'label'],
  'subject_label_type': ['type'],
  'tag': None,
  'state': None,
  'name_alias': ['nameAlias'],
  'tag.replace("_"': ['tag']},
 'aci_interface_policy_bfd': {'name': ['bfd_interface_policy'],
  'description': ['descr'],
  'admin_state': ['adminSt'],
  'detection_multiplier': None,
  'min_transmit_interval': None,
  'min_receive_interval': None,
  'state': None,
  'tenant': None},
 'aci_vlan_pool': {'pool': ['name', 'pool_name'],
  'description': ['descr'],
  'pool_allocation_mode': ['allocation_mode', 'mode'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_cloud_external_epg': {},
 'aci_domain_to_encap_pool': {'domain_type': None,
  'pool_type': None,
  'domain': ['domain_name', 'domain_profile'],
  'pool': ['pool_name'],
  'pool_allocation_mode': ['allocation_mode', 'mode'],
  'state': None,
  'vm_provider': None},
 'aci_tenant_span_src_group_to_dst_group': {'tenant': ['tenant_name'],
  'dst_group': ['name'],
  'src_group': None,
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_cloud_epg': {},
 'aci_vmm_vswitch_policy': {'port_channel_policy': None,
  'lldp_policy': None,
  'cdp_policy': None,
  'mtu_policy': None,
  'stp_policy': None,
  'enhanced_lag': None,
  'netflow_exporter': None,
  'domain': ['domain_name', 'domain_profile'],
  'state': None,
  'vm_provider': None,
  '"vswitchpolcont"': ['rn']},
 'aci_access_spine_interface_profile_to_spine_switch_profile': {'interface_profile_tDn': ['tDn']},
 'aci_fabric_pod': {'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias'],
  'pod_id': ['pod', 'id'],
  'pod_type': ['type'],
  'tep_pool': ['tep', 'pool']},
 'aci_fabric_switch_policy_group': {'name': ['policy_group',
   'policy_group_name'],
  'switch_type': None,
  'monitoring_policy': ['monitoring', 'fabricRsMonInstFabricPol'],
  'tech_support_export_policy': ['tech_support',
   'tech_support_export',
   'fabricRsNodeTechSupP'],
  'core_export_policy': ['core', 'core_export', 'fabricRsNodeCoreP'],
  'inventory_policy': ['inventory', 'fabricRsCallhomeInvPol'],
  'power_redundancy_policy': ['power_redundancy', 'fabricRsPsuInstPol'],
  'twamp_server_policy': ['twamp_server', 'fabricRsTwampServerPol'],
  'twamp_responder_policy': ['twamp_responder', 'fabricRsTwampResponderPol'],
  'node_control_policy': ['node_control', 'fabricRsNodeCtrl'],
  'analytics_cluster': None,
  'analytics_name': None,
  'description': ['descr'],
  'state': None},
 'aci_l3out_logical_interface_profile_ospf_policy': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['interface_profile_name', 'logical_interface'],
  'ospf_policy': ['name', 'ospf_policy_name'],
  'ospf_auth_type': None,
  'ospf_auth_key': None,
  'state': None},
 'aci_system_banner': {'description': ['descr'],
  'gui_alias': ['guiTextMessage'],
  'controller_banner': None,
  'switch_banner': None,
  'application_banner': ['bannerMessage'],
  'severity': ['bannerMessageSeverity'],
  'gui_banner': ['guiMessage'],
  'name_alias': None,
  'state': None,
  '"no" if re.fullmatch(regex_url': ['isGuiMessageText']},
 'aci_contract_export': {'name': ['interface_name'],
  'destination_tenant': None,
  'description': ['descr'],
  'tenant': ['tenant_name'],
  'contract': ['contract_name'],
  'state': None},
 'aci_domain_to_vlan_pool': {'domain_type': None,
  'domain': ['domain_name', 'domain_profile'],
  'pool': ['pool_name', 'vlan_pool'],
  'pool_allocation_mode': ['allocation_mode', 'mode'],
  'state': None,
  'vm_provider': None},
 'aci_l3out_hsrp_interface_profile': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['interface_profile_name', 'logical_interface'],
  'hsrp_policy': ['name', 'hsrp_policy_name'],
  'version': ['version'],
  'state': None},
 'aci_l3out_extsubnet': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'extepg': ['extepg_name', 'name'],
  'network': ['address', 'ip'],
  'description': ['descr'],
  'subnet_name': ['name'],
  'scope': None,
  'aggregate': None,
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_key_policy': {'tenant': ['tenant_name'],
  'keychain_policy': ['keychain_policy_name'],
  'id': ['id'],
  'start_time': ['startTime'],
  'end_time': ['endTime'],
  'pre_shared_key': None,
  'description': ['descr'],
  'state': None},
 'aci_l3out_logical_interface_profile': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['name', 'interface_profile_name', 'logical_interface'],
  'nd_policy': None,
  'egress_dpp_policy': None,
  'ingress_dpp_policy': None,
  'qos_priority': ['priority', 'prio'],
  'qos_custom_policy': ['qos_custom_policy_name'],
  '_interface_profile': None,
  'igmp_interface_profile': None,
  'state': None,
  'description': ['descr']},
 'aci_l3out_static_routes': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'logical_node': ['node_profile', 'node_profile_name'],
  'pod_id': None,
  'node_id': None,
  'prefix': ['route'],
  'track_policy': None,
  'preference': ['pref'],
  'bfd': None,
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_interface_policy_pim': {'tenant': ['tenant_name'],
  'pim': ['pim_interface_policy', 'name'],
  'description': ['descr'],
  'authentication_key': ['auth_key'],
  'authentication_type': ['auth_type'],
  'control_state': ['ctrl'],
  'designated_router_delay': ['delay'],
  'designated_router_priority': ['prio'],
  'hello_interval': ['helloItvl'],
  'join_prune_interval': ['jp_interval'],
  'inbound_join_prune_filter_policy': ['inbound_filter'],
  'outbound_join_prune_filter_policy': ['outbound_filter'],
  'neighbor_filter_policy': ['neighbor_filter'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_epg': {'epg': ['epg_name', 'name'],
  'bd': ['bd_name', 'bridge_domain'],
  'ap': ['app_profile', 'app_profile_name'],
  'tenant': ['tenant_name'],
  'description': ['descr'],
  'priority': ['prio'],
  'intra_epg_isolation': ['pcEnfPref'],
  'fwd_control': ['fwdCtrl'],
  'preferred_group': ['prefGrMemb'],
  'state': None,
  'name_alias': ['nameAlias'],
  'monitoring_policy': None,
  'custom_qos_policy': None,
  'useg': ['isAttrBasedEPg'],
  'match': None,
  'precedence': None},
 'aci_match_as_path_regex_term': {'tenant': ['tenant_name'],
  'match_rule': ['match_rule_name'],
  'match_as_path_regex_term': ['name', 'match_as_path_regex_term_name'],
  'regex': ['regex'],
  'description': ['descr'],
  'name_alias': ['nameAlias'],
  'state': None},
 'aci_fabric_span_src_group': {'source_group': ['name', 'src_group'],
  'description': ['descr'],
  'admin_state': ['adminSt'],
  'destination_group': ['dst_group'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_cloud_subnet': {'name': ['subnet'],
  'description': ['descr'],
  'address': ['ip'],
  'name_alias': ['nameAlias'],
  'vnet_gateway': None,
  'tenant': None,
  'cloud_context_profile': None,
  'cidr': None,
  'state': None,
  'aws_availability_zone': ['availability_zone', 'av_zone', 'zone'],
  'azure_region': ['az_region'],
  '"private"': ['scope'],
  'usage': ['usage']},
 'aci_aep_to_domain': {'aep': ['aep_name'],
  'domain': ['domain_name', 'domain_profile'],
  'domain_type': ['type'],
  'state': None,
  'vm_provider': None,
  'domain_mo': ['tDn']},
 'aci_aaa_security_default_settings': {'password_strength_check': ['pwdStrengthCheck'],
  'password_strength_profile': None,
  'options': None,
  'enable': ['minimum_length', 'min'],
  'type': ['maximum_length', 'max'],
  'min_length': ['flags'],
  'name_alias': ['nameAlias']},
 'aci_cloud_bgp_asn': {},
 'aci_aaa_user_certificate': {'aaa_user': None,
  'aaa_user_type': None,
  'certificate': ['cert_data', 'certificate_data'],
  'name': ['name'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_fabric_pod_remote_pool': {'pod_id': ['pod'],
  'description': ['desc'],
  'remote_id': ['id'],
  'name_alias': ['nameAlias'],
  'remote_pool': ['pool'],
  'state': None},
 'aci_config_export_policy': {'name': ['name'],
  'description': ['descr'],
  'format': ['format'],
  'target_dn': ['targetDn'],
  'snapshot': ['snapshot'],
  'export_destination': None,
  'scheduler': None,
  'start_now': ['adminSt'],
  'state': None},
 'aci_netflow_record_policy': {'tenant': ['tenant_name'],
  'netflow_record_policy': ['netflow_record', 'netflow_record_name', 'name'],
  'collect': ['collect'],
  'match': ['match'],
  'description': ['descr'],
  'state': None},
 'aci_firmware_group_node': {'group': None,
  'node': ['from_'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_filter': {'filter': ['name', 'filter_name'],
  'tenant': ['tenant_name'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias'],
  'filter_name': ['name']},
 'aci_fabric_switch_block': {'name': ['block_name'],
  'switch_type': None,
  'profile': ['profile_name', 'switch_profile'],
  'association': ['association_name', 'switch_association'],
  'description': ['descr'],
  'from_node': ['from', 'from_'],
  'to_node': ['to', 'to_'],
  'state': None,
  'descr': ['descr']},
 'aci_esg': {'tenant': ['tenant_name'],
  'ap': ['app_profile', 'app_profile_name'],
  'esg': ['name', 'esg_name'],
  'admin_state': None,
  'vrf': ['vrf_name'],
  'description': ['descr'],
  'shutdown': ['shutdown'],
  'intra_esg_isolation': ['pcEnfPref'],
  'preferred_group_member': ['prefGrMemb'],
  'name_alias': ['nameAlias']},
 'aci_aep_to_epg': {'aep': ['aep_name'],
  'tenant': ['tenant_name'],
  'ap': ['app_profile', 'app_profile_name'],
  'epg': ['epg_name'],
  'encap': ['vlan', 'vlan_id', 'encap_id'],
  'primary_encap': ['primary_vlan', 'primary_vlan_id', 'primary_encap_id'],
  '"default"': ['name']},
 'aci_config_snapshot': {'description': ['descr'],
  'export_policy': ['name'],
  'format': None,
  'include_secure': ['includeSecureFields'],
  'max_count': ['maxSnapshotCount'],
  'snapshot': ['name'],
  'state': None,
  '"triggered"': ['adminSt'],
  'file_format': ['format'],
  '"yes"': ['snapshot']},
 'aci_cloud_aws_provider': {},
 'aci_epg_to_contract_master': {'tenant': ['tenant_name'],
  'ap': ['app_profile', 'app_profile_name'],
  'epg': ['epg_name', 'name'],
  'contract_master_ap': None,
  'contract_master_epg': None,
  'state': None,
  'contract_master': ['tDn']},
 'aci_fabric_management_access_https_cipher': {'fabric_management_access_policy_name': ['name'],
  'id': None,
  'cipher_state': ['state'],
  'name_alias': ['nameAlias'],
  'state': None,
  'id_value': ['id']},
 'aci_interface_policy_lldp': {'lldp_policy': ['name'],
  'description': ['descr'],
  'receive_state': ['adminRxSt'],
  'transmit_state': ['adminTxSt'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_system_endpoint_controls': {'ip_aging': None,
  'options': None,
  'admin_state': None,
  'roque_ep_control': None},
 'aci_access_spine_switch_selector': {'spine_switch_profile': ['spine_switch_profile_name',
   'switch_profile',
   'switch_profile_name'],
  'description': ['descr'],
  'spine_switch_selector': ['name'],
  'selector_type': ['type']},
 'aci_vmm_uplink_container': {'domain': None,
  'num_of_uplinks': ['numOfUplinks'],
  'state': None},
 'aci_interface_policy_port_security': {'port_security': ['name'],
  'description': ['descr'],
  'max_end_points': ['maximum'],
  'port_security_timeout': ['timeout'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_tenant_span_src_group': {'tenant': ['tenant_name'],
  'src_group': ['name'],
  'admin_state': ['adminSt'],
  'description': ['descr'],
  'dst_group': None,
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_vmm_controller': {'name': ['name'],
  'controller_hostname': ['hostOrIp'],
  'dvs_version': ['dvsVersion'],
  'stats_collection': ['statsMode'],
  'domain': ['domain_name', 'domain_profile'],
  'state': None,
  'credentials': None,
  'inband_management_epg': None,
  'name_alias': ['nameAlias'],
  'datacenter': ['rootContName'],
  'vm_provider': None,
  'VM_SCOPE_MAPPING.get(vm_provider': ['scope']},
 'aci_vmm_uplink': {'domain': None,
  'uplink_id': ['uplinkId'],
  'uplink_name': ['uplinkName'],
  'state': None},
 'aci_netflow_monitor_policy': {'tenant': ['tenant_name'],
  'netflow_monitor_policy': ['netflow_monitor',
   'netflow_monitor_name',
   'name'],
  'netflow_record_policy': ['netflow_record', 'netflow_record_name'],
  'description': ['descr'],
  'state': None},
 'aci_pim_route_map_policy': {'tenant': ['tenant_name'],
  'pim_route_map_policy': ['route_map_policy_name', 'name'],
  'description': ['descr'],
  'state': None},
 'aci_static_binding_to_epg': {'tenant': ['tenant_name'],
  'ap': ['app_profile', 'app_profile_name'],
  'epg': ['epg_name'],
  'description': ['descr'],
  'encap_id': ['vlan', 'vlan_id'],
  'primary_encap_id': ['primary_vlan', 'primary_vlan_id'],
  'deploy_immediacy': ['instrImedcy'],
  'interface_mode': ['mode'],
  'static_path': ['tDn']},
 'aci_contract_subject': {'tenant': ['tenant_name'],
  'contract': ['contract_name'],
  'subject': ['contract_subject', 'name', 'subject_name'],
  'reverse_filter': None,
  'description': ['descr'],
  'consumer_match': None,
  'provider_match': None,
  'state': None,
  'name_alias': None,
  'apply_both_direction': None},
 'aci_bfd_multihop_node_policy': {'name': ['bfd_multihop_node_policy'],
  'description': ['descr'],
  'admin_state': ['adminSt'],
  'detection_multiplier': None,
  'min_transmit_interval': None,
  'min_receive_interval': None,
  'state': None,
  'tenant': None},
 'aci_access_spine_interface_selector': {'spine_interface_profile': ['spine_interface_profile_name',
   'interface_profile',
   'interface_profile_name'],
  'description': ['descr'],
  'spine_interface_selector': ['name'],
  'selector_type': ['type']},
 'aci_match_community_factor': {'tenant': ['tenant_name'],
  'match_rule': ['match_rule_name'],
  'match_community_term': ['match_community_term_name'],
  'community': ['community'],
  'scope': ['scope'],
  'description': ['descr'],
  'name_alias': ['nameAlias'],
  'state': None},
 'aci_fabric_interface_policy_group': {'name': ['policy_group'],
  'description': ['descr'],
  'name_alias': ['nameAlias'],
  'type': ['policy_group_type'],
  'dwdm_policy': None,
  'link_level_policy': None,
  'link_flap_policy': None,
  '_interface_policy': None,
  'macsec_policy': None,
  'monitoring_policy': None,
  'transceiver_policy_tdn': None,
  'state': None},
 'aci_aaa_key_ring': {'name': ['key_ring', 'key_ring_name'],
  'cloud_tenant': ['tenant_name', 'tenant'],
  'description': ['descr'],
  'certificate': ['cert_data', 'certificate_data', 'cert'],
  'modulus': ['modulus'],
  'certificate_authority': ['cert_authority',
   'cert_authority_name',
   'certificate_authority_name'],
  'key': ['key'],
  'key_type': None,
  'ecc_curve': ['curve'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_l3out_floating_svi_path_secondary_ip': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['interface_profile_name', 'logical_interface'],
  'state': None,
  'pod_id': None,
  'node_id': None,
  'encap': None,
  'domain_type': None,
  'domain': None,
  'secondary_ip': ['secondary_floating_address'],
  '"disabled"': ['ipv6Dad']},
 'aci_l3out_interface_secondary_ip': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['interface_profile_name', 'logical_interface'],
  'state': None,
  'pod_id': None,
  'node_id': None,
  'path_ep': None,
  'side': None,
  'address': ['addr', 'ip_address'],
  '_dad': None,
  'ipv6_dad': ['ipv6Dad']},
 'aci_interface_policy_hsrp': {'tenant': ['tenant_name'],
  'hsrp': ['hsrp_interface', 'name'],
  'description': ['descr'],
  'controls': ['ctrl'],
  'reload_delay': ['reloadDelay'],
  'delay': ['delay'],
  'state': None},
 'aci_qos_custom_policy': {'tenant': ['tenant_name'],
  'qos_custom_policy': ['qos_custom_policy_name', 'name'],
  'description': ['descr'],
  'state': None},
 'aci_interface_policy_l2': {'_policy': ['name'],
  'description': ['descr'],
  'vlan_scope': ['vlanScope'],
  'qinq': ['qinq'],
  'vepa': ['vepa'],
  'state': None,
  'name_alias': ['nameAlias'],
  'l2_policy': ['name']},
 'aci_cloud_provider': {'state': None},
 'aci_syslog_group': {'name': ['syslog_group', 'syslog_group_name'],
  'format': ['format'],
  'admin_state': None,
  'console_logging': None,
  'console_log_severity': None,
  'local_file_logging': None,
  'include_ms': ['includeMilliSeconds']},
 'aci_filter_entry': {'arp_flag': ['arpOpc'],
  'description': ['descr'],
  'destination_port': ['dst_port'],
  'destination_port_end': ['dst_port_end'],
  'destination_port_start': ['dst_port_start'],
  'source_port': ['src_port'],
  'source_port_end': ['src_port_end'],
  'source_port_start': ['src_port_start'],
  'tcp_flags': None,
  'match_only_fragments': ['applyToFrag'],
  'entry': ['entry_name', 'filter_entry', 'name'],
  'ether_type': ['etherT'],
  'filter': ['filter_name'],
  'icmp_msg_type': ['icmpv4T'],
  '_msg_type': None,
  'ip_protocol': ['prot'],
  'state': None,
  'stateful': ['stateful'],
  'tenant': ['tenant_name'],
  'name_alias': ['nameAlias'],
  'dst_port_start': ['dFromPort'],
  'dst_port_end': ['dToPort'],
  'icmp6_msg_type': ['icmpv6T'],
  '"': ['tcpRules']},
 'aci_system_connectivity_preference': {'interface_preference': ['interfacePref']},
 'aci_vrf': {'tenant': ['tenant_name'],
  'vrf': ['context', 'name', 'vrf_name'],
  'description': ['descr'],
  'policy_control_direction': ['pcEnfDir'],
  'policy_control_preference': ['pcEnfPref'],
  'state': None,
  'preferred_group': None,
  'match_type': None,
  'name_alias': ['nameAlias'],
  'ip_data_plane_learning': ['ip_dataplane_learning']},
 'aci_interface_policy_leaf_profile': {'interface_profile': ['name',
   'leaf_interface_profile_name',
   'leaf_interface_profile',
   'interface_profile_name'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias'],
  'type': None},
 'aci_cloud_ap': {'description': ['descr'],
  'name': ['app_profile', 'app_profile_name', 'ap'],
  'tenant': ['tenant_name'],
  'state': None},
 'aci_l3out': {'tenant': ['tenant_name'],
  'out': ['l3out_name', 'name'],
  'domain': ['ext_routed_domain_name', 'routed_domain'],
  'vrf': ['vrf_name'],
  'description': ['descr'],
  'l3out': ['name'],
  'enforce_ctrl': ['enforceRtctrl'],
  'mpls': ['mplsEnabled'],
  'dscp': ['targetDscp'],
  'name_alias': ['nameAlias']},
 'aci_interface_policy_fc': {'fc_policy': ['name'],
  'description': ['descr'],
  'port_mode': ['portMode'],
  'auto_max_speed': ['automaxspeed'],
  'fill_pattern': ['fillPattern'],
  'buffer_credits': ['rxBBCredit'],
  'speed': ['speed'],
  'trunk_mode': ['trunkMode'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_fabric_external_connection_profile': {'description': ['descr'],
  'fabric_id': ['id', 'fabric'],
  'name': ['profile_name'],
  'community': ['rt', 'route_target'],
  'site_id': ['sid', 'site', 's_id'],
  'peering_type': ['p_type', 'peer', 'peer_t'],
  'peering_password': ['peer_password', 'peer_pwd'],
  'state': None},
 'aci_interface_policy_link_level': {'link_level_policy': ['name'],
  'description': ['descr'],
  'auto_negotiation': ['autoNeg'],
  'speed': ['speed'],
  'link_debounce_interval': ['linkDebounce'],
  'forwarding_error_correction': ['fecMode']},
 'aci_switch_policy_vpc_protection_group': {'protection_group': ['name',
   'protection_group_name'],
  'protection_group_id': ['id'],
  'vpc_domain_policy': ['vpc_domain_policy_name'],
  '_id': None,
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_tenant_span_src_group_src': {'description': ['descr'],
  'direction': None,
  'name': ['name'],
  'src_ap': ['ap'],
  'src_epg': ['epg'],
  'src_group': None,
  'state': None,
  'tenant': ['tenant_name'],
  'SPAN_DIRECTION_MAP.get(direction': ['dir']},
 'aci_tenant_action_rule_profile': {'action_rule': ['action_rule_name',
   'name'],
  'tenant': ['tenant_name'],
  'set_community': None,
  'set_dampening': None,
  'set_next_hop': None,
  'next_hop_propagation': None,
  'multipath': None,
  'set_preference': None,
  'set_metric': None,
  'set_metric_type': None,
  'set_route_tag': None,
  'set_weight': None,
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_keychain_policy': {'tenant': ['tenant_name'],
  'keychain_policy': ['keychain_policy_name', 'name'],
  'description': ['descr'],
  'state': None},
 'aci_netflow_monitor_to_exporter': {'tenant': ['tenant_name'],
  'netflow_monitor_policy': ['netflow_monitor',
   'netflow_monitor_name',
   'name'],
  'netflow_exporter_policy': ['netflow_exporter', 'netflow_exporter_name'],
  'state': None},
 'aci_fabric_pod_profile': {'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias'],
  'name': ['profile', 'pod_profile']},
 'aci_interface_policy_leaf_breakout_port_group': {'breakout_port_group': ['name'],
  'description': ['descr'],
  'breakout_map': ['brkoutMap'],
  'state': None},
 'aci_fabric_management_access': {'name': ['fabric_management_access_policy_name'],
  'description': ['descr'],
  'name_alias': ['nameAlias'],
  'http': None,
  'options': None,
  'admin_state': None,
  'port': None,
  'redirect': None,
  'allow_origins': None,
  'allow_credentials': None,
  'throttle': None},
 'aci_interface_policy_mcp': {'mcp': ['mcp_interface', 'name'],
  'description': ['descr'],
  'admin_state': ['adminSt'],
  'mcp_mode': ['mcpMode'],
  'grace_period': ['gracePeriod'],
  'grace_period_millisec': ['grace_period_msec', 'gracePeriodMsec'],
  'init_delay_time': ['strict_init_delay_time', 'strictInitDelayTime'],
  'tx_frequence': ['strict_tx_freq', 'strictTxFreq'],
  'tx_frequence_millisec': ['strict_tx_freq_msec', 'strictTxFreqMsec'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_fabric_span_src_group_src_node': {'source_group': ['src_group'],
  'source': ['src'],
  'pod': ['pod_id', 'pod_number'],
  'node': ['node_id'],
  'state': None,
  'tdn': ['tDn']},
 'aci_interface_policy_storm_control': {'storm_control_policy': ['name'],
  'description': ['descr'],
  'name_alias': ['nameAlias'],
  'storm_control_types': ['isUcMcBcStormPktCfgValid'],
  'storm_control_action': ['stormCtrlAction'],
  'storm_control_soak_action': ['stormCtrlSoakInstCount']},
 'aci_l3out_hsrp_secondary_vip': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['interface_profile_name', 'logical_interface'],
  'hsrp_interface_group': ['name', 'hsrp_group'],
  'secondary_virtual_ip': ['vip', 'secondary_vip'],
  'state': None},
 'aci_maintenance_policy': {'name': ['maintenance_policy'],
  'run_mode': ['runmode'],
  'graceful': ['graceful'],
  'scheduler': None,
  'ignore_compat': ['ignoreCompat'],
  'admin_state': ['adminSt'],
  'download_state': ['downloadSt'],
  'notify_condition': ['notifCond'],
  'smu_operation': ['smuOperation'],
  'smu_operation_flags': ['smuOperationFlags'],
  'sr_upgrade': ['srUpgrade'],
  'sr_version': ['srVersion'],
  'version': ['version'],
  'version_check_override': ['versionCheckOverride'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_action_rule_set_as_path': {'tenant': ['tenant_name'],
  'action_rule': ['action_rule_name'],
  'last_as': ['last_as_number'],
  'criteria': ['criteria'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_l3out_floating_svi_secondary_ip': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['interface_profile_name', 'logical_interface'],
  'state': None,
  'pod_id': None,
  'node_id': None,
  'encap': None,
  'secondary_ip': ['secondary_floating_address'],
  '"enabled"': ['ipv6Dad']},
 'aci_netflow_exporter_policy': {'tenant': ['tenant_name'],
  'netflow_exporter_policy': ['netflow_exporter',
   'netflow_exporter_name',
   'name'],
  'dscp': ['dscp'],
  'destination_address': ['dstAddr'],
  'destination_port': ['dstPort'],
  'source_ip_type': ['sourceIpType'],
  'custom_source_address': ['srcAddr'],
  'associated_epg': ['epg'],
  'associated_extepg': ['external_epg', 'associated_external_epg'],
  'associated_vrf': ['vrf', 'associated_context', 'context'],
  'description': ['descr'],
  'state': None},
 'aci_interface_policy_leaf_fc_policy_group': {'lag_type': ['lag_type_name'],
  'policy_group': ['name', 'policy_group_name'],
  'description': ['descr'],
  'fibre_channel_interface_policy': ['fibre_channel_interface_policy_name'],
  'port_channel_policy': ['port_channel_policy_name'],
  'attached_entity_profile': ['aep_name', 'aep'],
  'state': None,
  'name_alias': None},
 '__init__': {},
 'aci_access_span_filter_group_entry': {'filter_group': None,
  'source_ip': ['srcAddr'],
  'destination_ip': ['dstAddr'],
  'first_src_port': ['srcPortFrom'],
  'last_src_port': ['srcPortTo'],
  'first_dest_port': ['dstPortFrom'],
  'last_dest_port': ['dstPortTo'],
  'ip_protocol': ['ipProto'],
  'name_alias': ['nameAlias'],
  'state': None},
 'aci_cloud_vpn_gateway': {'tenant': None,
  'cloud_context_profile': None,
  'state': None,
  '"default"': ['name']},
 'aci_cloud_cidr': {'address': ['cidr'],
  'description': ['descr'],
  'name_alias': ['nameAlias'],
  'tenant': None,
  'cloud_context_profile': None,
  'state': None,
  '"no"': ['primary']},
 'aci_esg_tag_selector': {'tenant': ['tenant_name'],
  'ap': ['app_profile', 'app_profile_name'],
  'esg': ['esg_name'],
  'name': ['match_key'],
  'operator': ['value_operator'],
  'match_value': ['matchValue'],
  'description': ['tag_selector_description']},
 'aci_ap': {'tenant': ['tenant_name'],
  'ap': ['app_profile', 'app_profile_name', 'name'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias'],
  'monitoring_policy': None},
 'aci_tenant_span_dst_group': {'tenant': ['tenant_name'],
  'destination_epg': None,
  'destination_group': ['name', 'dst_group'],
  'description': ['descr'],
  'name_alias': ['nameAlias'],
  'source_ip': None,
  'destination_ip': None,
  'mtu': None,
  'ttl': None,
  'flow_id': None,
  'version_enforced': None,
  'span_version': None},
 'aci_interface_policy_bfd_multihop': {'name': ['bfd_multihop_interface_policy'],
  'description': ['descr'],
  'admin_state': ['adminSt'],
  'detection_multiplier': None,
  'min_transmit_interval': None,
  'min_receive_interval': None,
  'state': None,
  'tenant': None},
 'aci_match_community_regex_term': {'tenant': ['tenant_name'],
  'match_rule': ['match_rule_name'],
  'match_community_regex_term': ['name', 'match_community_regex_term_name'],
  'community_type': ['commType'],
  'regex': ['regex'],
  'description': ['descr'],
  'name_alias': ['nameAlias'],
  'state': None},
 'aci_route_control_profile': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'route_control_profile': ['name', 'route_control_profile_name'],
  'description': ['descr'],
  'auto_continue': ['autoContinue'],
  'policy_type': ['type'],
  'name_alias': ['nameAlias'],
  'state': None},
 'aci_epg_useg_attribute_simple_statement': {'ap': ['app_profile',
   'app_profile_name'],
  'epg': ['epg_name'],
  'state': None,
  'tenant': ['tenant_name'],
  'parent_block_statements': ['parent_blocks', 'blocks'],
  'name': ['useg_attribute_name'],
  'type': None,
  'operator': None,
  'category': ['custom_attribute'],
  'value': None,
  'use_subnet': None},
 'aci_l3out_to_sr_mpls_infra_l3out': {'tenant': ['tenant_name'],
  'out': ['infra_l3out_name'],
  'description': ['descr'],
  'external_epg': ['external_epg_dn'],
  'outbound_route_map': ['outbound_route_map_dn', 'outbound'],
  'inbound_route_map': ['inbound_route_map_dn', 'inbound'],
  'state': None,
  'name_alias': ['nameAlias'],
  'infra_l3out': ['name']},
 'aci_access_span_src_group_src': {'source_group': ['src_group'],
  'description': ['descr'],
  'source': ['name', 'src'],
  'direction': None,
  'filter_group': None,
  'drop_packets': None,
  'epg': ['tenant_name'],
  'options': ['ap_name', 'app_profile', 'app_profile_name'],
  'SPAN_DIRECTION_MAP.get(direction': ['dir']},
 'aci_fabric_span_dst_group': {'destination_group': ['name', 'dst_group'],
  'description': ['descr'],
  'destination_epg': None,
  'name_alias': ['nameAlias'],
  'state': None},
 'aci_taboo_contract': {'taboo_contract': ['name'],
  'tenant': ['tenant_name'],
  'scope': ['scope'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_fabric_span_src_group_src_path': {'source_group': ['src_group'],
  'source': ['src'],
  'pod': ['pod_id', 'pod_number'],
  'node': ['node_id'],
  'path_ep': None,
  'state': None,
  'tdn': ['tDn']},
 'aci_contract': {'contract': ['contract_name', 'name'],
  'tenant': ['tenant_name'],
  'description': ['descr'],
  'scope': ['scope'],
  'priority': ['prio'],
  'dscp': ['targetDscp'],
  'name_alias': ['nameAlias']},
 'aci_fabric_node': {'description': ['descr'],
  'node_id': ['nodeId'],
  'pod_id': ['podId'],
  'role': ['role_name'],
  'node_type': None,
  'remote_leaf_pool_id': ['pool_id'],
  'serial': ['serial_number'],
  'switch': ['name', 'switch_name'],
  'state': None,
  'name_alias': None,
  '"uni/controller/nodeidentpol/nodep-{0}".format(serial': ['dn']},
 'aci_interface_policy_eigrp': {'tenant': ['tenant_name'],
  'eigrp': ['eigrp_interface', 'name'],
  'description': ['descr'],
  'bandwidth': ['bw'],
  'control_state': ['ctrl'],
  'delay': ['delay'],
  'delay_unit': ['delayUnit'],
  'hello_interval': ['helloIntvl'],
  'hold_interval': ['holdIntvl'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_dhcp_option_policy': {'tenant': ['tenant_name'],
  'dhcp_option_policy': ['dhcp_option_policy_name', 'name'],
  'description': ['descr'],
  'state': None},
 'aci_access_spine_switch_profile': {'switch_profile': ['name'],
  'description': ['descr'],
  'name_alias': ['nameAlias']},
 'aci_epg_to_contract_interface': {'tenant': ['tenant_name'],
  'ap': ['app_profile', 'app_profile_name'],
  'epg': ['epg_name'],
  'contract_interface': ['contract_interface_name'],
  'priority': ['prio'],
  'state': None},
 'aci_firmware_group': {'group': ['name'],
  'policy': ['firmwarepol'],
  'type_group': ['type'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_firmware_policy': {'name': ['name'],
  'description': ['descr'],
  'version': ['version'],
  'effective_on_reboot': ['effectiveOnReboot'],
  'ignore_compat': ['ignoreCompat'],
  'sr_upgrade': ['srUpgrade'],
  'sr_version': ['srVersion'],
  'version_check_override': ['versionCheckOverride'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_aaa_custom_privilege': {'name': ['custom_privilege_name'],
  'description': ['descr'],
  'w_priv': ['wPriv'],
  'r_priv': ['rPriv'],
  'name_alias': ['nameAlias']},
 'aci_bgp_rr_asn': {'asn': ['asn'], 'state': None},
 'aci_bgp_route_summarization_policy': {'tenant': ['tenant_name'],
  'route_summarization_policy': ['route_summarization_policy_name', 'name'],
  'address_type_af_control': ['address_type_control'],
  'control_state': ['summary_control', 'control'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_interface_policy_ospf': {'tenant': ['tenant_name'],
  'ospf': ['ospf_interface', 'name'],
  'description': ['descr'],
  'network_type': ['nwT'],
  'cost': ['cost'],
  'controls': ['ctrl'],
  'dead_interval': ['deadIntvl'],
  'hello_interval': ['helloIntvl'],
  'prefix_suppression': ['pfxSuppress'],
  'priority': ['prio'],
  'retransmit_interval': ['rexmitIntvl'],
  'transmit_delay': ['xmitDelay'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_dns_provider': {'dns_profile': ['profile_name'],
  'address': ['addr', 'ip_address'],
  'preferred': ['preferred'],
  'state': None},
 'aci_snmp_user': {'policy': ['snmp_policy', 'snmp_policy_name'],
  'name': ['snmp_user_policy'],
  'description': ['descr'],
  'auth_type': ['authType'],
  'auth_key': ['authKey'],
  'privacy_type': ['privType'],
  'privacy_key': ['privKey'],
  'state': None},
 'aci_l3out_static_routes_nexthop': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'pod_id': None,
  'node_id': None,
  'prefix': ['route'],
  'nexthop': ['nhAddr'],
  'state': None},
 'aci_epg_to_contract': {'contract_type': None,
  'ap': ['app_profile', 'app_profile_name'],
  'epg': ['epg_name'],
  'contract': ['contract_name', 'contract_interface'],
  'priority': None,
  'provider_match': None,
  'state': None,
  'tenant': ['tenant_name'],
  'contract_label': None,
  'subject_label': None},
 'aci_epg_subnet': {'tenant': ['tenant_name'],
  'epg': ['epg_name', 'name'],
  'ap': ['app_profile', 'app_profile_name'],
  'description': ['descr'],
  'enable_vip': ['virtual'],
  'gateway': ['gateway_ip'],
  'mask': ['subnet_mask'],
  'subnet_name': ['name'],
  'nd_prefix_policy': None,
  'preferred': ['preferred'],
  'route_profile': None,
  'out': None,
  'scope': ['scope'],
  'subnet_control': ['ctrl'],
  'state': None,
  'ip_data_plane_learning': ['ip_dataplane_learning'],
  'name_alias': ['nameAlias']},
 'aci_node_mgmt_epg': {'type': None,
  'epg': ['name'],
  'bd': None,
  'encap': ['encap'],
  'state': None},
 'aci_vrf_multicast': {'tenant': ['tenant_name'],
  'vrf': ['vrf_name'],
  'pim_setting': None,
  'options': ['control', 'ctrl'],
  'mtu': ['mtu'],
  'control_state': ['ctrl']},
 'aci_l3out_bgp_protocol_profile': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'bgp_timers_policy': ['bgp_timers_policy_name'],
  'bgp_best_path_policy': ['bgp_best_path_policy_name'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_cloud_region': {'region': ['name'], 'cloud': None, 'state': None},
 'aci_encap_pool_range': {'pool_type': ['type'],
  'allocation_mode': ['mode'],
  'description': ['descr'],
  'pool': ['pool_name'],
  'pool_allocation_mode': ['pool_mode'],
  'range_end': ['end'],
  'range_name': ['name', 'range'],
  'range_start': ['start'],
  'state': None,
  'name_alias': None},
 'aci_access_span_dst_group': {'destination_group': ['name', 'dst_group'],
  'description': ['descr'],
  'access_interface': None,
  'destination_epg': None,
  'name_alias': ['nameAlias'],
  'state': None},
 'aci_dns_profile': {'dns_profile': ['name', 'profile_name'], 'state': None},
 'aci_vzany_to_contract': {'tenant': ['tenant_name'],
  'vrf': ['context', 'vrf_name'],
  'contract': ['contract_name'],
  'type': ['contract_type'],
  'state': None},
 'aci_switch_policy_leaf_profile': {'leaf_profile': ['name',
   'leaf_profile_name'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_contract_subject_to_service_graph': {'tenant': None,
  'contract': None,
  'subject': None,
  'service_graph': ['tnVnsAbsGraphName'],
  'state': None},
 'aci_syslog_remote_dest': {'name': ['remote_destination_name',
   'remote_destination'],
  'format': ['format'],
  'admin_state': ['adminState'],
  'description': ['descr'],
  'destination': ['host'],
  'facility': ['forwardingFacility'],
  'group': ['syslog_group', 'syslog_group_name'],
  'mgmt_epg': None,
  'syslog_port': ['port'],
  'severity': ['severity'],
  'state': None},
 'aci_vlan_pool_encap_block': {'pool': ['pool_name'],
  'block_name': ['name'],
  'block_end': ['end'],
  'block_start': ['start'],
  'allocation_mode': ['mode'],
  'description': ['descr'],
  'pool_allocation_mode': ['pool_mode'],
  'state': None,
  'name_alias': None},
 'aci_system': {'id': ['controller', 'node'], 'state': None},
 'aci_interface_config': {'policy_group': ['policy_group_name'],
  'breakout': ['brkoutMap'],
  'description': ['descr'],
  'node': ['node_id'],
  'pc_member': ['port_channel_member'],
  'port_type': None,
  'role': ['node_type'],
  'admin_state': None,
  'policy_group_dn': ['assocGrp'],
  'card': ['card'],
  'port_id': ['port'],
  'ADMIN_STATE_MAPPING.get(admin_state': ['shutdown']},
 'aci_pim_route_map_entry': {'tenant': ['tenant_name'],
  'pim_route_map_policy': ['route_map_policy_name'],
  'description': ['descr'],
  'order': ['order'],
  'source_ip': ['src'],
  'group_ip': ['grp'],
  'rp_ip': ['rendezvous_point_ip'],
  'action': ['action'],
  'state': None},
 'aci_l3out_logical_node_profile': {'node_profile': ['name',
   'node_profile_name',
   'logical_node'],
  'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'description': ['descr'],
  'dscp': ['targetDscp'],
  'name_alias': ['nameAlias']},
 'aci_maintenance_group_node': {'group': None,
  'node': ['from_'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_interface_policy_leaf_profile_fex_policy_group': {'name': ['policy_group'],
  'fex_profile': None,
  'state': None},
 'aci_cloud_epg_selector': {},
 'aci_snmp_policy': {'name': ['snmp_policy', 'snmp_policy_name'],
  'admin_state': ['adminSt'],
  'contact': ['contact'],
  'description': ['descr'],
  'location': ['loc'],
  'state': None},
 'aci_l3out_floating_svi_path': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['interface_profile_name', 'logical_interface'],
  'state': None,
  'pod_id': None,
  'node_id': None,
  'encap': None,
  'floating_ip': ['floating_address'],
  'forged_transmit': ['forgedTransmit'],
  'mac_change': ['macChange'],
  'promiscuous_mode': ['promMode'],
  'domain_type': None,
  'domain': None,
  'enhanced_lag_policy': None,
  'access_encap': ['encap']},
 'aci_file_remote_path': {'name': ['name'],
  'description': ['descr'],
  'remote_host': ['host'],
  'remote_port': ['remotePort'],
  'remote_protocol': ['protocol'],
  'remote_path': ['remotePath'],
  'auth_type': None,
  'remote_user': ['userName'],
  'remote_password': ['userPasswd'],
  'remote_ssh_key': ['remote_key'],
  'remote_ssh_passphrase': ['passphrase'],
  'management_epg': None,
  'state': None,
  'auth': ['authType'],
  'remote_key': ['identityPrivateKeyContents'],
  'passphrase': ['identityPrivateKeyPassphrase']},
 'aci_action_rule_additional_communities': {'tenant': ['tenant_name'],
  'action_rule': ['action_rule_name'],
  'community': ['community'],
  'criteria': ['setCriteria'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_maintenance_group': {'group': ['name'],
  'policy': ['maintenancepol'],
  'firmware_nodes_type': ['fwtype'],
  'type_group': ['type'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_bulk_static_binding_to_epg': {'tenant': ['tenant_name'],
  'ap': ['app_profile', 'app_profile_name'],
  'epg': ['epg_name'],
  'description': ['descr'],
  'encap_id': ['vlan', 'vlan_id'],
  'primary_encap_id': ['primary_vlan', 'primary_vlan_id'],
  'deploy_immediacy': None},
 'aci_tag': {'dn': None,
  'tag_key': None,
  'tag_value': None,
  'tag_type': None,
  'state': None},
 'aci_fabric_leaf_profile': {'name': ['leaf_switch_profile', 'leaf_profile'],
  'description': ['descr'],
  'state': None},
 'aci_interface_selector_to_switch_policy_leaf_profile': {'leaf_profile': ['leaf_profile_name'],
  'interface_selector': ['interface_profile_name',
   'interface_selector_name',
   'name'],
  'state': None,
  'interface_selector_tDn': ['tDn']},
 'aci_access_sub_port_block_to_access_port': {'leaf_interface_profile': ['leaf_interface_profile_name'],
  'access_port_selector': ['name', 'access_port_selector_name'],
  'leaf_port_blk': ['leaf_port_blk_name'],
  'leaf_port_blk_description': ['descr'],
  'from_port': ['from', 'fromPort', 'from_port_range'],
  'to_port': ['to', 'toPort', 'to_port_range'],
  'from_sub_port': ['fromSubPort', 'from_sub_port_range'],
  'to_sub_port': ['toSubPort', 'to_sub_port_range'],
  'from_card': ['from_card_range'],
  'to_card': ['to_card_range'],
  'state': None,
  '': ['type']},
 'aci_match_route_destination': {'tenant': ['tenant_name'],
  'match_rule': ['match_rule_name'],
  'ip': ['ip'],
  'aggregate': ['aggregate'],
  'from_prefix_length': ['fromPfxLen'],
  'to_prefix_length': ['toPfxLen'],
  'description': ['descr'],
  'name_alias': ['nameAlias'],
  'state': None},
 'aci_fabric_span_src_group_src': {'source_group': ['src_group'],
  'description': ['descr'],
  'source': ['name', 'src'],
  'direction': None,
  'drop_packets': None,
  'vrf': ['vrf_name'],
  'options': ['tenant_name'],
  'SPAN_DIRECTION_MAP.get(direction': ['dir']},
 'aci_aaa_certificate_authority': {'name': ['name'],
  'description': ['descr'],
  'certificate_chain': ['certChain'],
  'name_alias': ['nameAlias']},
 'aci_bd_to_netflow_monitor_policy': {'bd': ['bd_name', 'bridge_domain'],
  'netflow_monitor_policy': ['netflow_monitor',
   'netflow_monitor_name',
   'name'],
  'filter_type': ['filter', 'type'],
  'tenant': ['tenant_name'],
  'state': None},
 'aci_bd_subnet': {'bd': ['bd_name'],
  'description': ['descr'],
  'enable_vip': ['virtual'],
  'gateway': ['gateway_ip'],
  'mask': ['subnet_mask'],
  'subnet_name': ['name'],
  'nd_prefix_policy': None,
  'preferred': ['preferred'],
  'route_profile': None,
  '_out': None,
  'scope': ['scope'],
  'subnet_control': ['ctrl'],
  'state': None,
  'tenant': ['tenant_name'],
  'name_alias': ['nameAlias'],
  'ip_data_plane_learning': ['ip_dataplane_learning']},
 'aci_l3out_bfd_multihop_interface_profile': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'out_logical_node_profile': ['logical_node_profile_name',
   'logical_node_profile'],
  'out_logical_interface_profile': ['logical_interface_profile_name',
   'logical_interface_profile'],
  'name': ['bfd_multihop_interface_profile'],
  'name_alias': ['nameAlias'],
  'description': ['descr'],
  'authentication_type': ['type'],
  'key': ['key'],
  'key_id': None,
  'bfd_multihop_interface_policy': ['multihop_interface_policy',
   'multihop_interface_policy_name'],
  'state': None},
 'aci_cloud_zone': {'name': ['zone'],
  'cloud': None,
  'region': None,
  'state': None},
 'aci_encap_pool': {'pool_type': ['type'],
  'description': ['descr'],
  'pool': ['name', 'pool_name'],
  'pool_allocation_mode': ['allocation_mode', 'mode'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_bgp_rr_node': {'node_id': ['id'],
  'pod_id': ['podId'],
  'description': ['descr'],
  'state': None},
 'aci_fabric_pod_connectivity_profile': {'pod_id': ['pod', 'pid'],
  'fabric_id': ['fabric', 'fid'],
  'virtual_pod_id': ['vpod', 'vpod_id'],
  'description': ['descr'],
  'data_plane_tep': ['dp_tep'],
  'unicast_tep': ['u_tep'],
  'state': None},
 'aci_contract_subject_to_filter': {'tenant': ['tenant_name'],
  'contract': ['contract_name'],
  'filter': ['filter_name'],
  'subject': ['contract_subject', 'subject_name'],
  'direction': None,
  'action': None,
  'directives': ['log', 'directive'],
  'priority_override': None,
  'state': None},
 'aci_dns_domain': {'dns_profile': ['profile_name'],
  'domain': ['name', 'domain_name'],
  'default': ['isDefault'],
  'state': None},
 'aci_fabric_wide_settings': {'disable_remote_ep_learning': ['unicastXrEpLearnDisable'],
  'enforce_subnet_check': ['enforceSubnetCheck'],
  'enforce_epg_vlan_validation': ['validateOverlappingVlans'],
  'enforce_domain_validation': ['domainValidation'],
  'spine_opflex_client_auth': ['opflexpAuthenticateClients'],
  'leaf_opflex_client_auth': ['leafOpflexpAuthenticateClients'],
  'spine_ssl_opflex': ['opflexpUseSsl'],
  'leaf_ssl_opflex': ['leafOpflexpUseSsl'],
  'opflex_ssl_versions': None,
  'reallocate_gipo': ['reallocateGipo'],
  'restrict_infra_vlan_traffic': ['restrictInfraVLANTraffic'],
  'state': None},
 'aci_aaa_user_domain': {'aaa_user': ['user_name'],
  'name': ['domain_name', 'user_domain'],
  'aaa_user_type': None,
  'name_alias': ['nameAlias'],
  'state': None},
 'aci_action_rule_set_as_path_asn': {'tenant': ['tenant_name'],
  'action_rule': ['action_rule_name'],
  'asn': ['asn'],
  'order': ['order'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_domain': {'domain_type': ['type'],
  'domain': ['domain_name', 'domain_profile', 'name'],
  'encap_mode': ['encapMode'],
  'multicast_address': ['mcastAddr'],
  'add_infra_pg': ['configInfraPg'],
  'tag_collection': ['enableTag'],
  'vswitch': ['mode'],
  'dscp': ['targetDscp'],
  'name_alias': ['nameAlias'],
  'access_mode': ['accessMode'],
  'enable_vm_folder': ['enableVmFolder']},
 'aci_match_community_term': {'tenant': ['tenant_name'],
  'match_rule': ['match_rule_name'],
  'match_community_term': ['name', 'match_community_term_name'],
  'description': ['descr'],
  'name_alias': ['nameAlias'],
  'state': None},
 'aci_access_port_to_interface_policy_leaf_profile': {'interface_profile': ['leaf_interface_profile_name',
   'leaf_interface_profile',
   'interface_profile_name'],
  'access_port_selector': ['name', 'access_port_selector_name'],
  'description': ['descr'],
  'port_blk': ['leaf_port_blk_name', 'leaf_port_blk', 'port_blk_name'],
  'leaf_port_blk_description': None,
  'from_port': ['from', 'fromPort', 'from_port_range'],
  'to_port': ['to', 'toPort', 'to_port_range'],
  'from_card': ['from_card_range'],
  'to_card': ['to_card_range'],
  'policy_group': ['policy_group_name'],
  '': ['type']},
 'aci_l3out_interface': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['interface_profile_name', 'logical_interface'],
  'state': None,
  'pod_id': None,
  'node_id': None,
  'path_ep': None,
  'address': ['addr', 'ip_address'],
  'mtu': ['mtu'],
  '_dad': None,
  'interface_type': ['ifInstT'],
  'mode': ['mode'],
  'encap': ['encap'],
  'encap_scope': None,
  'auto_state': ['autostate'],
  'description': ['descr'],
  'mac': ['mac_address'],
  'micro_bfd': None,
  'micro_bfd_destination': ['micro_bfd_address',
   'micro_bfd_destination_address'],
  'micro_bfd_timer': ['micro_bfd_start_timer', 'micro_bfd_start'],
  'path_dn': ['tDn'],
  'ipv6_dad': ['ipv6Dad'],
  '"ctx" if encap_scope == "vrf" else encap_scope': ['encapScope']},
 'aci_fabric_spine_switch_assoc': {'profile': ['spine_profile',
   'spine_switch_profile'],
  'name': ['association_name', 'switch_association'],
  'policy_group': None,
  'description': ['descr'],
  'state': None},
 'aci_interface_policy_cdp': {'cdp_policy': ['cdp_interface', 'name'],
  'description': ['descr'],
  'admin_state': ['adminSt'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_l3out_extepg_to_contract': {'contract_type': None,
  'out': ['l3out_name'],
  'contract': ['contract_name', 'contract_interface'],
  'priority': None,
  'provider_match': None,
  'state': None,
  'tenant': None,
  'extepg': ['extepg_name', 'external_epg'],
  'contract_label': None,
  'subject_label': None},
 'aci_aaa_role': {'name': ['aaa_role'],
  'privileges': ['priv'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias'],
  'formatted_privileges': ['priv']},
 'aci_config_rollback': {'compare_export_policy': None,
  'compare_snapshot': None,
  'description': ['descr'],
  'export_policy': None,
  'fail_on_decrypt': ['failOnDecryptErrors'],
  'import_mode': ['importMode'],
  'import_policy': ['name'],
  'import_type': ['importType'],
  'snapshot': None,
  'state': None,
  '"triggered"': ['adminSt'],
  'filename': ['fileName'],
  '"yes"': ['snapshot']},
 'aci_snmp_client_group': {'client_group': ['client_group_name',
   'client_group_profile'],
  'mgmt_epg': ['management_epg_name', 'management_epg'],
  'policy': ['snmp_policy', 'snmp_policy_name'],
  'description': ['descr'],
  'state': None},
 'aci_tenant_ep_retention_policy': {'tenant': ['tenant_name'],
  'epr_policy': ['epr_name', 'name'],
  'bounce_age': ['bounceAgeIntvl'],
  'bounce_trigger': ['bounceTrig'],
  'hold_interval': ['holdIntvl'],
  'local_ep_interval': ['localEpAgeIntvl'],
  'remote_ep_interval': ['remoteEpAgeIntvl'],
  'description': ['descr'],
  'move_frequency': ['moveFreq'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_access_spine_interface_profile': {'interface_profile': ['name'],
  'description': ['descr'],
  'name_alias': ['nameAlias']},
 'aci_aaa_domain': {'name': ['aaa_domain'],
  'description': ['descr'],
  'restricted_rbac_domain': None,
  'state': None,
  'name_alias': ['nameAlias'],
  'restricted_rbac_domain_state': ['restrictedRbacDomain']},
 'aci_access_port_block_to_access_port': {'port_blk_description': ['descr'],
  'port_blk': ['name'],
  'from_port': ['fromPort'],
  'to_port': ['toPort'],
  'from_card': ['fromCard'],
  'to_card': ['toCard']},
 'aci_ntp_server': {'ntp_policy': ['policy_name'],
  'ntp_server': ['server_name'],
  'description': ['descr'],
  'min_poll': ['minPoll'],
  'max_poll': ['maxPoll'],
  'preferred': ['preferred'],
  'epg_type': None,
  'epg_name': None,
  'state': None},
 'aci_bd_to_l3out': {'bd': ['bd_name', 'bridge_domain'],
  'out': None,
  'tenant': ['tenant_name'],
  'state': None,
  'l3out': ['tnL3extOutName']},
 'aci_bgp_address_family_context_policy': {'tenant': ['tenant_name'],
  'address_family_context_policy': ['address_family_context_name', 'name'],
  'host_route_leak': ['ctrl'],
  'ebgp_distance': ['eDist'],
  'ibgp_distance': ['iDist'],
  'local_distance': ['localDist'],
  'ebgp_max_ecmp': ['maxEcmp'],
  'ibgp_max_ecmp': ['maxEcmpIbgp'],
  'local_max_ecmp': ['maxLocalEcmp'],
  'bgp_add_path_capability': None,
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_rest': {'path': ['uri'],
  'method': ['action'],
  'src': ['config_file'],
  'content': None,
  'rsp_subtree_preserve': None},
 'aci_access_switch_policy_group': {'name': ['policy_group'],
  'description': ['descr'],
  'switch_type': None,
  'spanning_tree_policy': None,
  '_policy': None,
  'fibre_channel_node_policy': None,
  'poe_node_policy': None,
  'fibre_channel_san_policy': None,
  'monitoring_policy': None,
  'netflow_node_policy': None,
  'copp_policy': None,
  'forward_scale_profile_policy': None,
  'fast_link_failover_policy': None,
  'x_authentication_policy': None,
  'copp_pre_filter_policy': None,
  'equipment_flash_policy': None,
  'cdp_policy': None,
  'lldp_policy': None,
  'sync_e_node_policy': None,
  'ptp_node_policy': None,
  'usb_configuration_policy': None,
  'state': None},
 'aci_fabric_pod_selector': {'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias'],
  'pod_profile': None,
  'name': ['selector', 'pod_selector'],
  'type': None,
  'blocks': ['pod_id', 'pod_id_range'],
  'policy_group': None,
  'selector_type': ['type']},
 'aci_l3out_logical_interface_vpc_member': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['interface_profile_name', 'logical_interface'],
  'path_dn': None,
  'pod_id': None,
  'node_id': None,
  'path_ep': None,
  'side': ['name'],
  'address': ['addr', 'ip_address'],
  '_dad': None,
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias'],
  'ipv6_dad': ['ipv6Dad']},
 'aci_snmp_community_policy': {'community': ['name'],
  'policy': ['snmp_policy', 'snmp_policy_name'],
  'description': ['descr'],
  'state': None},
 'aci_tenant': {'tenant': ['name', 'tenant_name'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_snmp_client': {'address': ['addr'],
  'client_group': ['client_group_name', 'client_group_profile'],
  'policy': ['snmp_policy', 'snmp_policy_name'],
  'client_name': ['name'],
  'state': None},
 'aci_qos_dot1p_class': {'tenant': ['tenant_name'],
  'qos_custom_policy': ['qos_custom_policy_name']},
 'aci_epg_useg_attribute_block_statement': {'ap': ['app_profile',
   'app_profile_name'],
  'epg': ['epg_name'],
  'state': None,
  'tenant': ['tenant_name'],
  'parent_block_statements': ['parent_blocks', 'blocks'],
  'name': ['block_statement', 'block_statement_name'],
  'match': ['match']},
 'aci_route_control_context': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'route_control_profile': ['route_control_profile_name'],
  'route_control_context': ['name', 'route_control_context_name', 'context'],
  'match_rule': ['match_rule_name'],
  'action_rule': ['action_rule_name'],
  'action': ['action'],
  'order': ['order'],
  'description': ['descr'],
  'name_alias': ['nameAlias'],
  'state': None},
 'aci_qos_dscp_class': {'tenant': ['tenant_name'],
  'qos_custom_policy': ['qos_custom_policy_name']},
 'aci_l2out_extepg_to_contract': {'contract_type': None,
  'out': ['l2out_name'],
  'contract': ['tnVzBrCPName'],
  'priority': ['prio'],
  'provider_match': ['matchT'],
  'state': None,
  'tenant': None,
  'extepg': ['extepg_name', 'external_epg']},
 'aci_l2out_logical_interface_profile': {'tenant': ['tenant_name'],
  'out': ['l2out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['name', 'interface_profile_name', 'logical_interface'],
  'state': None},
 'aci_l3out_logical_node': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'pod_id': None,
  'node_id': None,
  'router_id': ['rtrId'],
  'router_id_as_loopback': ['rtrIdLoopBack'],
  'loopback_address': ['loopback'],
  'mpls_transport_loopback_address': ['mpls_transport_loopback'],
  'sid': ['segment_id'],
  'state': None,
  'tdn': ['tDn']},
 'aci_interface_policy_spanning_tree': {'stp_policy': ['name'],
  'description': ['descr'],
  'bpdu_guard': None,
  'bpdu_filter': None,
  'state': None,
  'name_alias': ['nameAlias'],
  'ctrl': ['ctrl']},
 'aci_l3out_eigrp_interface_profile': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['interface_profile_name', 'logical_interface'],
  'eigrp_policy': ['name', 'eigrp_policy_name'],
  'eigrp_keychain_policy': ['keychain_policy', 'keychain_policy_name'],
  'description': ['descr'],
  'state': None},
 'aci_interface_policy_leaf_policy_group': {'lag_type': ['lag_type_name'],
  'policy_group': ['name', 'policy_group_name'],
  'description': ['descr'],
  'link_level_policy': ['link_level_policy_name'],
  'cdp_policy': ['cdp_policy_name'],
  'mcp_policy': ['mcp_policy_name'],
  'lldp_policy': ['lldp_policy_name'],
  'stp_interface_policy': ['stp_interface_policy_name'],
  'egress_data_plane_policing_policy': ['egress_data_plane_policing_policy_name'],
  'ingress_data_plane_policing_policy': ['ingress_data_plane_policing_policy_name'],
  'priority_flow_control_policy': ['priority_flow_control_policy_name'],
  'fibre_channel_interface_policy': ['fibre_channel_interface_policy_name'],
  'slow_drain_policy': ['slow_drain_policy_name'],
  'port_channel_policy': ['port_channel_policy_name'],
  'monitoring_policy': ['monitoring_policy_name'],
  'storm_control_interface_policy': ['storm_control_interface_policy_name'],
  '_interface_policy': ['l2_interface_policy_name'],
  'port_security_policy': ['port_security_policy_name'],
  'link_flap_policy': ['link_flap_policy_name'],
  'link_level_flow_control': ['link_level_flow_control_name'],
  'mac_sec_interface_policy': ['mac_sec_interface_policy_name'],
  'copp_policy': ['copp_policy_name'],
  'aep': ['aep_name'],
  'sync_e_interface_policy': ['sync_e_interface_policy_name'],
  'transceiver_policy': ['transceiver_policy_name'],
  'options': ['transceiver_policy_type']},
 'aci_aaa_user': {'aaa_password': ['pwd'],
  'aaa_password_lifetime': ['pwdLifeTime'],
  'aaa_password_update_required': ['pwdUpdateRequired'],
  'aaa_user': ['name'],
  'clear_password_history': ['clearPwdHistory'],
  'description': ['descr'],
  'email': ['email'],
  'enabled': ['accountStatus'],
  'expiration': ['expiration'],
  'expires': ['expires'],
  'first_name': ['firstName'],
  'last_name': ['lastName'],
  'phone': ['phone'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_ntp_policy': {'name': ['ntp_policy'],
  'description': ['descr'],
  'admin_state': ['adminSt'],
  'server_state': ['serverState'],
  'auth_state': ['authSt'],
  'master_mode': ['masterMode'],
  'state': None},
 'aci_fabric_scheduler': {'name': ['scheduler_name'],
  'description': ['descr'],
  'windowname': None,
  'recurring': None,
  'concurCap': None,
  'maxTime': None,
  'date': None,
  'state': None,
  'hour': None,
  'minute': None,
  'name_alias': ['nameAlias']},
 'aci_aep': {'aep': ['name', 'aep_name'],
  'description': ['descr'],
  'infra_vlan': ['infrastructure_vlan'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_l3out_extepg': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'extepg': ['extepg_name', 'name'],
  'description': ['descr'],
  'preferred_group': ['prefGrMemb'],
  'dscp': ['targetDscp'],
  'name_alias': ['nameAlias'],
  'qos_class': ['prio'],
  'contract_exception_tag': ['exceptionTag']},
 'aci_fabric_external_routing_profile': {'name': ['routing_profile',
   'profile'],
  'fabric_id': ['fabric', 'fid'],
  'description': ['descr'],
  'subnets': ['ip_addresses', 'ips'],
  'state': None},
 'aci_bgp_best_path_policy': {'tenant': ['tenant_name'],
  'bgp_best_path_policy': ['bgp_best_path_policy_name', 'name'],
  'best_path_control': ['as_path_control'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_fabric_leaf_switch_assoc': {'profile': ['leaf_profile',
   'leaf_switch_profile'],
  'name': ['association_name', 'switch_association'],
  'policy_group': None,
  'description': ['descr'],
  'state': None},
 'aci_access_span_src_group': {'source_group': ['name', 'src_group'],
  'description': ['descr'],
  'admin_state': ['adminSt'],
  'filter_group': None,
  'destination_group': ['dst_group'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_bgp_peer_prefix_policy': {'tenant': ['tenant_name'],
  'peer_prefix_policy': ['peer_prefix_policy_name', 'name'],
  'action': ['action'],
  'maximum_number_prefix': ['max_prefix', 'max_num_prefix'],
  'restart_time': ['restartTime'],
  'threshold': ['thresh'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_cloud_external_epg_selector': {},
 'aci_esg_to_contract': {'contract_type': None,
  'tenant': ['tenant_name'],
  'ap': ['app_profile', 'app_profile_name'],
  'esg': ['esg_name'],
  'contract': ['contract_name', 'contract_interface'],
  'priority': None,
  'state': None},
 'aci_fabric_spine_profile': {'name': ['spine_switch_profile',
   'spine_profile'],
  'description': ['descr'],
  'state': None},
 'aci_node_block': {'description': ['descr'],
  'node_block': ['name'],
  'from_port': ['from_'],
  'to_port': ['to_']},
 'aci_esg_epg_selector': {'tenant': ['tenant_name'],
  'ap': ['app_profile', 'app_profile_name'],
  'esg': ['esg_name'],
  'epg_ap': None,
  'epg': ['epg_name'],
  'description': ['epg_selector_description'],
  'matchEpgDn': ['matchEpgDn']},
 'aci_aaa_user_role': {'aaa_user': ['user_name'],
  'aaa_user_type': None,
  'domain_name': ['user_domain'],
  'name': ['role_name', 'user_role'],
  'privilege_type': ['priv_type'],
  'name_alias': ['nameAlias'],
  'state': None},
 'aci_dhcp_relay': {'name': ['relay_policy'],
  'description': ['descr'],
  'state': None,
  'tenant': None,
  'owner': ['owner']},
 'aci_l3out_dhcp_relay_label': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['interface_profile_name', 'logical_interface'],
  'dhcp_relay_label': ['name', 'relay_policy'],
  'scope': ['owner'],
  'dhcp_option_policy': ['dhcp_option_policy_name'],
  'description': ['descr'],
  'state': None},
 'aci_aaa_ssh_auth': {'aaa_user': None,
  'auth_name': ['name'],
  'data': ['data'],
  'state': None},
 'aci_epg_monitoring_policy': {'monitoring_policy': ['name'],
  'tenant': ['tenant_name'],
  'description': ['descr'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_interface_policy_port_channel': {'port_channel': ['name'],
  'description': ['descr'],
  'min_links': ['minLinks'],
  'max_links': ['maxLinks'],
  'mode': ['mode'],
  'fast_select': None,
  'graceful_convergence': None,
  'load_defer': None,
  'suspend_individual': None,
  'symmetric_hash': None,
  'state': None,
  'name_alias': ['nameAlias'],
  'ctrl': ['ctrl']},
 'aci_access_span_filter_group': {'filter_group': ['name'],
  'name_alias': ['nameAlias'],
  'state': None},
 'aci_l2out_extepg': {'out': None,
  'description': None,
  'extepg': ['external_epg', 'extepg_name', 'name'],
  'preferred_group': None,
  'state': None,
  'tenant': None,
  'qos_class': None},
 'aci_interface_description': {'pod_id': ['pod', 'pod_number'],
  'node_id': ['leaf', 'spine', 'node'],
  'fex_id': None,
  'node_type': None,
  'interface': None,
  'description': ['descr'],
  'state': None},
 'aci_l3out_route_tag_policy': {'tenant': ['tenant_name'],
  'rtp': ['name', 'rtp_name'],
  'description': ['descr'],
  'tag': ['tag'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_epg_to_domain': {'allow_useg': ['classPref'],
  'ap': ['app_profile', 'app_profile_name'],
  'deploy_immediacy': ['instrImedcy'],
  'domain': ['domain_name', 'domain_profile'],
  'domain_type': ['type'],
  'encap': ['encap'],
  'encap_mode': ['encapMode'],
  'switching_mode': ['switchingMode'],
  'epg': ['name', 'epg_name'],
  'enhanced_lag_policy': ['lag_policy'],
  'vmm_uplink_active': None,
  'vmm_uplink_standby': None,
  'netflow': ['netflowPref'],
  'primary_encap': ['primaryEncap'],
  'resolution_immediacy': ['resImedcy'],
  'state': None,
  'tenant': ['tenant_name'],
  'vm_provider': None,
  'promiscuous': None,
  'custom_epg_name': ['customEpgName'],
  'delimiter': ['delimiter'],
  'untagged_vlan': ['untagged'],
  'port_binding': ['bindingType'],
  'port_allocation': ['portAllocation'],
  'number_of_ports': ['numPorts'],
  'forged_transmits': None,
  'mac_changes': None},
 'aci_fabric_node_control': {'name': ['fabric_node_control'],
  'description': ['descr'],
  'enable_dom': ['control'],
  'feature_selection': ['feature'],
  'state': None},
 'aci_interface_policy_spine_policy_group': {'policy_group': ['policy_group_name',
   'spine_policy_group_name',
   'name'],
  'description': ['descr'],
  'name_alias': ['nameAlias'],
  'link_level_policy': ['link_level_policy_name'],
  'link_flap_policy': ['link_flap_policy_name'],
  'cdp_policy': ['cdp_policy_name'],
  'mac_sec_policy': ['mac_sec_policy_name'],
  'attached_entity_profile': ['aep_name', 'aep'],
  'state': None},
 'aci_l2out_logical_node_profile': {'tenant': ['tenant_name'],
  'out': ['l2out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'state': None},
 'aci_cloud_ctx_profile': {'description': ['descr'],
  'name': ['name'],
  'name_alias': ['name_alias'],
  '"regular"': ['type']},
 'aci_static_node_mgmt_address': {'node_id': None,
  'pod_id': None,
  'type': None,
  'epg': None,
  '_address': ['ipv6'],
  '_gw': None,
  'state': None,
  'ipv4_address': ['addr'],
  'ipv4_gw': ['gw'],
  'ipv6_address': ['v6Addr'],
  'ipv6_gw': ['v6Gw']},
 'aci_access_span_src_group_src_path': {'source_group': ['src_group'],
  'source': ['src'],
  'pod': ['pod_id', 'pod_number'],
  'nodes': ['node_ids'],
  'path_ep': None,
  'state': None,
  'tdn': ['tDn']},
 'aci_fabric_pod_external_tep': {'description': ['descr'],
  'name_alias': ['nameAlias'],
  'pod_id': ['pod'],
  'external_tep_pool': ['ip', 'ip_address', 'tep_pool', 'pool'],
  'reserve_address_count': ['address_count'],
  'status': ['state'],
  'state': None,
  'descr': ['descr']},
 'aci_dhcp_option': {'tenant': ['tenant_name'],
  'dhcp_option_policy': ['dhcp_option_policy_name'],
  'dhcp_option': ['dhcp_option_name', 'name'],
  'data': ['data'],
  'id': ['id'],
  'state': None},
 'aci_dhcp_relay_provider': {'relay_policy': ['relay_policy_name'],
  'epg_type': None,
  'anp': None,
  'epg': ['app_epg'],
  'out_name': None,
  'external_epg': ['external_net'],
  'dhcp_server_addr': ['addr'],
  'state': None,
  'tenant': None,
  'provider_tenant': None,
  'dn': None,
  'tdn': ['tDn']},
 'aci_bd': {'arp_flooding': ['arpFlood'],
  'bd': ['bd_name', 'name'],
  'bd_type': ['type'],
  'description': ['descr'],
  'enable_multicast': ['mcastAllow'],
  'enable_routing': ['unicastRoute'],
  'endpoint_clear': ['epClear'],
  'endpoint_move_detect': ['epMoveDetectMode'],
  'endpoint_retention_action': None,
  'endpoint_retention_policy': None,
  'igmp_snoop_policy': None,
  'ip_learning': ['ipLearning'],
  '_nd_policy': None,
  '_unknown_unicast': None,
  '_unknown_multicast': None,
  'limit_ip_learn': ['limitIpLearnToSubnets'],
  'mac_address': ['mac'],
  'multi_dest': ['multiDstPktAct'],
  'state': None,
  'tenant': ['tenant_name'],
  'vrf': ['vrf_name'],
  'route_profile': None,
  'out': None,
  'name_alias': ['nameAlias'],
  'host_based_routing': ['advertise_host_routes'],
  'enable_rogue_except_mac': ['enableRogueExceptMac'],
  'allow_intersite_bum_traffic': ['allow_bum_traffic'],
  '_stretch': ['allow_l2_stretch'],
  '_multicast': ['ipv6_multicast', 'ipv6_mcast', 'allow_ipv6_mcast'],
  'link_local_address': ['ll_addr_ipv6', 'll_addr', 'link_local'],
  'multicast_arp_drop': ['mcast_arp_drop'],
  'vmac': ['vmac'],
  'optimize_wan_bandwidth': ['wan_optimization', 'opt_bandwidth'],
  'mld_snoop_policy': ['mld_snoop', 'mld_policy'],
  'igmp_policy': ['igmp'],
  'vlan': ['encap'],
  'monitoring_policy': ['mon_pol', 'monitoring_pol'],
  'first_hop_security_policy': ['fhsp', 'fhs_pol', 'fhsp_name'],
  'pim_source_filter': ['pim_source'],
  'pim_destination_filter': ['pim_dest', 'pim_destination'],
  'l2_unknown_unicast': ['unkMacUcastAct'],
  'l3_unknown_multicast': ['unkMcastAct'],
  'allow_intersite_l2_stretch': ['intersiteL2Stretch'],
  'allow_ipv6_multicast': ['ipv6McastAllow']},
 'aci_vrf_leak_internal_subnet': {'tenant': ['tenant_name'],
  'vrf': ['context', 'name', 'vrf_name'],
  'leak_to': ['vrf_name'],
  'options': ['tenant_name'],
  'description': ['descr'],
  'ip': ['ip'],
  'scope': ['scope'],
  'name_alias': ['nameAlias']},
 'aci_esg_ip_subnet_selector': {'tenant': ['tenant_name'],
  'ap': ['app_profile', 'app_profile_name'],
  'esg': ['esg_name'],
  'ip': ['subnet'],
  'description': ['ip_subnet_selector_description'],
  'match_expression': ['matchExpression']},
 'aci_syslog_source': {'name': ['syslog_src', 'syslog_source'],
  'include': None,
  'min_severity': ['minSev'],
  'destination_group': None,
  'state': None},
 'aci_bd_dhcp_label': {'bd': ['bd_name'],
  'description': ['descr'],
  'dhcp_label': ['name'],
  'dhcp_option': None,
  'scope': ['owner'],
  'state': None,
  'tenant': ['tenant_name']},
 'aci_igmp_interface_policy': {'name': ['name'],
  'tenant': None,
  'description': ['descr'],
  'group_timeout': ['grpTimeout'],
  'query_interval': ['queryIntvl'],
  'query_response_interval': ['rspIntvl'],
  'last_member_count': ['lastMbrCnt'],
  'last_member_response': ['lastMbrRespTime'],
  'startup_query_count': ['startQueryCnt'],
  'startup_query_interval': ['startQueryIntvl'],
  'querier_timeout': ['querierTimeout'],
  'robustness_variable': ['robustFac'],
  'igmp_version': ['ver'],
  '_asm': None,
  'fast_leave': None,
  'report_link_local_groups': None,
  'state': None,
  'if_ctrl': ['ifCtrl']},
 'aci_vmm_credential': {'name': ['credential_name', 'credential_profile'],
  'credential_password': ['pwd'],
  'credential_username': ['usr'],
  'description': ['descr'],
  'domain': ['domain_name', 'domain_profile'],
  'state': None,
  'vm_provider': None,
  'name_alias': ['nameAlias']},
 'aci_interface_blacklist': {'pod_id': ['pod', 'pod_number'],
  'node_id': ['leaf', 'spine', 'node'],
  'fex_id': None,
  'interface': None,
  'state': None,
  '"blacklist"': ['lc']},
 'aci_system_global_aes_passphrase_encryption': {'passphrase': ['passphrase'],
  'enable': ['strongEncryptionEnabled'],
  'state': None},
 'aci_match_rule': {'tenant': ['tenant_name'],
  'match_rule': ['name', 'match_rule_name'],
  'description': ['descr'],
  'name_alias': ['nameAlias'],
  'state': None},
 'aci_l3out_bfd_interface_profile': {'tenant': ['tenant_name'],
  'out': ['l3out_name'],
  'out_logical_node_profile': ['logical_node_profile_name',
   'logical_node_profile'],
  'out_logical_interface_profile': ['logical_interface_profile_name',
   'logical_interface_profile'],
  'name': ['bfd_multihop_interface_profile'],
  'name_alias': ['nameAlias'],
  'description': ['descr'],
  'authentication_type': ['type'],
  'key': ['key'],
  'key_id': None,
  'bfd_interface_policy': ['interface_policy', 'interface_policy_name'],
  'state': None},
 'aci_l2out_logical_interface_path': {'tenant': ['tenant_name'],
  'out': ['l2out_name'],
  'node_profile': ['node_profile_name', 'logical_node'],
  'interface_profile': ['name', 'interface_profile_name', 'logical_interface'],
  'interface_type': None,
  'pod_id': ['pod', 'pod_number'],
  'leaves': ['leafs', 'nodes', 'paths', 'switches'],
  'interface': None,
  'state': None,
  'path': ['tDn']},
 'aci_firmware_source': {'source': ['name', 'source_name'],
  'polling_interval': ['pollingInterval'],
  'url': ['url'],
  'url_username': ['user'],
  'url_password': ['password'],
  'url_protocol': ['url_proto'],
  'state': None,
  'name_alias': ['nameAlias']},
 'aci_bd_rogue_exception_mac': {'bd': ['bd_name', 'bridge_domain'],
  'tenant': ['tenant_name'],
  'mac': ['mac'],
  'description': ['descr'],
  'state': None},
 'aci_switch_leaf_selector': {'description': ['descr'],
  'leaf': ['name'],
  'name_alias': ['nameAlias']}}